version: '3.9'


services:

#ForAll
  ZipkinForAll:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    environment:
      - OPENZIPKIN_BASE_URL=http://localhost:9411

#AuthServer
  AuthServerDB:
    image: postgres:latest

    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
  AuthServerRedis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

#UserInfo
  UserInfoDB:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user
    ports:
      - "5447:5432"
