spring:
  application:
   name: AuthServer
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG


