spring:
  application:
   name: UserInfoService
  datasource:
     url: jdbc:postgresql://localhost:5447/user
     username: root
     password: root
  jpa:
    show-sql: true
    properties:
     hibernate.hibernate.format_sql: true
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

