spring:
  application:
   name: UserInfoService
  datasource:
     url: jdbc:postgresql://localhost:5447/user
     username: root
     password: root
  jpa:
    show-sql: true
    properties:
     hibernate.hibernate.format_sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
    config:
      uri: http://localhost:9297
  config:
    import: "configserver:"

server:
  port: 8083
  servlet:
    context-path: /api/user



